# Общая конфигурация docker-compose для основного приложения

version: '3.3'
services:
  app:
    image: cr.yandex/crpg0pddi1l3221pa7qq/main/php:8.0.12-fpm-alpine3.13
    env_file:
      - .env
    volumes:
      - ./src:/app
    working_dir: /app

  db:
    image: cr.yandex/crpg0pddi1l3221pa7qq/public/postgres:11.9-pglogical-1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    volumes:
      - ./runtime/postgresql:/var/lib/postgresql/data
    ports:
      - "5444:5432"
