version: '3.3'

services:
  app:
    image: cr.yandex/crpg0pddi1l3221pa7qq/main/php:8.0.12-fpm-alpine3.13
    volumes:
      - ./:/app
    working_dir: /app
    command: [ "bash","-c","while true; do echo 'work'; sleep 2; done" ]

  postgres:
    image: cr.yandex/crpg0pddi1l3221pa7qq/public/postgres:11.9-pglogical-1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./runtime/postgresql/data:/var/lib/postgresql/data
